language: ruby
rvm:
  - 2.2.2
  - 1.9.3
gemfile:
  - test/gemfiles/Gemfile.chef-11
  - test/gemfiles/Gemfile.chef-10
  - test/gemfiles/Gemfile.chef-12
  - test/gemfiles/Gemfile.chef-master
matrix:
  allow_failures:
    - gemfile: test/gemfiles/Gemfile.chef-master
  exclude:
    - rvm: 1.9.3
      gemfile: test/gemfiles/Gemfile.chef-12
    - rvm: 1.9.3
      gemfile: test/gemfiles/Gemfile.chef-master

